name: website

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                persist-credentials: false
            - name: Sphinx
              run: |
                sudo apt-get install -y python3-setuptools 
                sudo -H pip3 install sphinx sphinxemoji recommonmark
            - name: Build
              run: | 
                cd Website && make html
                touch .nojekyll && mv .nojekyll build/html
            - name: Publish
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: Website/build/html
